-- CREACION DE BASE DE DATOS CEDBOS --
CREATE DATABASE CEDBOS;
USE CEDBOS;

CREATE TABLE Grupos (
	IdGrupo INT PRIMARY KEY NOT NULL,
    Nombre VARCHAR(40) NOT NULL
);

CREATE TABLE Users(
    IdUser INT PRIMARY KEY AUTO_INCREMENT,
    IdGrupo INT NOT NULL,
    User VARCHAR(50) NOT NULL,
    Name VARCHAR(50) NOT NULL, 
    lastName VARCHAR(50) NOT NULL,
    FullName VARCHAR(100) NOT NULL,
    Pass VARCHAR(200),
    Question VARCHAR(255) NOT NULL,
    Answer VARCHAR(255) NOT NULL,
    SuperUser BOOLEAN NOT NULL,
    CONSTRAINT fk_grupos FOREIGN KEY (IdGrupo) REFERENCES grupos (IdGrupo) ON DELETE CASCADE ON UPDATE CASCADE
    
);

CREATE TABLE HistorialDeAcciones (
	IdAct INT PRIMARY KEY AUTO_INCREMENT,
    IdUser INT NOT NULL,
    Descripcion TEXT NOT NULL,
    Accion VARCHAR(40) NOT NULL,
    CONSTRAINT fk_act FOREIGN KEY (IdUser) REFERENCES users (IdUser) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Integrantes (
	NIP INT PRIMARY KEY NOT NULL,
    IdGrupo INT NOT NULL,
    td CHAR(2) NOT NULL,
    nombres VARCHAR(60) NOT NULL,
    apellidos VARCHAR(60) NOT NULL,
    barrio VARCHAR(60) NOT NULL,
    municipio VARCHAR(60) NOT NULL,
    direccion VARCHAR(100) NOT NULL,
    telefono VARCHAR(30) NOT NULL,
    celular VARCHAR(30) NOT NULL,
    email VARCHAR(100) NOT NULL,
    nacimiento DATE NOT NULL,
    sexo CHAR(1) NOT NULL,
    CONSTRAINT fk_integrantes FOREIGN KEY (IdGrupo) REFERENCES grupos (IdGrupo) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Mercados(
    IdMer INT PRIMARY KEY NOT NULL,
    IdGrupo INT NOT NULL,
    Cantidad INT NOT NULL,
    CONSTRAINT fk_mercados	FOREIGN KEY (IdGrupo) REFERENCES grupos (IdGrupo) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Grados (
    IdGrado INT PRIMARY KEY NOT NULL,
    Grado VARCHAR(40) NOT NULL,
    AporteMonetario INT NOT NULL
);

CREATE TABLE Productos (
	IdProducto INT PRIMARY KEY NOT NULL,
    IdMer INT NOT NULL,
    IdGrado INT NOT NULL,
   	Cantidad INT NOT NULL,
    Tipo VARCHAR(40) NOT NULL,
    Marca VARCHAR(40) NOT NULL,
    Vencimiento DATE NOT NULL,
    CONSTRAINT fk_productos	FOREIGN KEY (IdMer) REFERENCES Mercados (IdMer) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_grados FOREIGN KEY (IdGrado) REFERENCES Grados (IdGrado)	ON DELETE CASCADE ON UPDATE CASCADE 
);
